<a href="https://colab.research.google.com/github/Oniscot/DRUG-/blob/main/Assignment_1_fixed_Onilude.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [3]:
from google.colab import drive

In [5]:
drive.mount('/content/gdrive/',force_remount=True)

Mounted at /content/gdrive/

In [51]:
!mkdir -p "/content/gdrive/MyDrive/Colab Notebooks/data"

mkdir: cannot create directory ‘/content/gdrive/MyDrive/Colab Notebooks/data’: File exists

In [7]:
pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.0-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.1.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-25.3.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.5.1)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 1.5 MB/s eta 0:00:00
Downloading requests_cache-1.3.0-py3-none-any.whl (69 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.6/69.6 kB 4.3 MB/s eta 0:00:00
Downloading cattrs-25.3.0-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.7/70.7 kB 6.0 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-25.3.0 chembl_webresource_client-0.10.9 requests-cache-1.3.0 url-normalize-2.2.1

In [8]:
import pandas as pd

In [9]:
from chembl_webresource_client.new_client import new_client

In [10]:
target = new_client.target

In [20]:
target_query=target.search("TP53")

In [21]:
targets = pd.DataFrame.from_dict(target_query)
targets.head()

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,TP53-binding protein 1,15.0,False,CHEMBL2424509,"[{'accession': 'Q12888', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Mus musculus,TP53-binding protein 1,15.0,False,CHEMBL4295790,"[{'accession': 'P70399', 'component_descriptio...",SINGLE PROTEIN,10090
2,[],Homo sapiens,"Fructose-2,6-bisphosphatase TIGAR",15.0,False,CHEMBL4295958,"[{'accession': 'Q9NQ88', 'component_descriptio...",SINGLE PROTEIN,9606
3,[],Homo sapiens,HCT 116 TP53(-/-),15.0,False,CHEMBL6066766,[],CELL-LINE,9606
4,[],Mus musculus,Cellular tumor antigen p53,14.0,False,CHEMBL4164,"[{'accession': 'P02340', 'component_descriptio...",SINGLE PROTEIN,10090

In [41]:
selected_target=targets.target_chembl_id[0]
selected_target

'CHEMBL2424509'

In [24]:
activity = new_client.activity

In [25]:
results=activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [26]:
df1=pd.DataFrame.from_dict(results)
display(df1.head())
print(f'Shape of df1: {df1.shape}')

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,13444885,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 ...,B,None,None,BAO_0000190,...,Homo sapiens,TP53-binding protein 1,9606,None,None,IC50,uM,UO_0000065,None,10.0
1,None,None,13444886,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 ...,B,None,None,BAO_0000190,...,Homo sapiens,TP53-binding protein 1,9606,None,None,IC50,uM,UO_0000065,None,3.5
2,None,None,13444887,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 ...,B,None,None,BAO_0000190,...,Homo sapiens,TP53-binding protein 1,9606,None,None,IC50,uM,UO_0000065,None,10.0
3,None,None,13444888,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 ...,B,None,None,BAO_0000190,...,Homo sapiens,TP53-binding protein 1,9606,None,None,IC50,uM,UO_0000065,None,10.0
4,None,None,13444889,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 ...,B,None,None,BAO_0000190,...,Homo sapiens,TP53-binding protein 1,9606,None,None,IC50,uM,UO_0000065,None,10.0

Shape of df1: (137, 46)

In [ ]:
df1.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1038874,[],CHEMBL798941,Inhibition of Serine/threonine-protein kinase ...,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase Chk2,9606,None,None,IC50,nM,UO_0000065,None,3000.0
1,None,None,1405011,[],CHEMBL874429,Inhibition of recombinant human Chk2 kinase,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase Chk2,9606,None,None,IC50,nM,UO_0000065,None,2400.0
2,None,None,1405012,[],CHEMBL874429,Inhibition of recombinant human Chk2 kinase,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase Chk2,9606,None,None,IC50,nM,UO_0000065,None,290.0
3,None,None,1405013,[],CHEMBL874429,Inhibition of recombinant human Chk2 kinase,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase Chk2,9606,None,None,IC50,nM,UO_0000065,None,55.0
4,None,None,1405014,[],CHEMBL874429,Inhibition of recombinant human Chk2 kinase,B,None,None,BAO_0000190,...,Homo sapiens,Serine/threonine-protein kinase Chk2,9606,None,None,IC50,nM,UO_0000065,None,1400.0

In [27]:
df1.standard_type.unique()

array(['IC50'], dtype=object)

In [28]:
df1.to_csv('bioactivity_raw_data.csv', index=False)

In [52]:
!cp bioactivity_raw_data.csv "/content/gdrive/MyDrive/Colab Notebooks/data"

In [54]:
!ls -l "/content/gdrive/MyDrive/Colab Notebooks/data"

-rw------- 1 root root 84403 Feb  8 22:47 '/content/gdrive/MyDrive/Colab Notebooks/data'

In [43]:
! head bioactivity_raw_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,13444885,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 mins by AlphaScreen assay,B,,,BAO_0000190,BAO_0000357,single protein format,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CCC(C5CCCN5)CC4)c(Nc4ccccc4)c3)cc2C1,,,CHEMBL2424619,J Med Chem,2013,,CHEMBL2424677,,CHEMBL2424677,,0,http://www.openphacts.org/units/Nanomolar,1919666,>,1,1,>,,IC50,nM,,10000.0,CHEMBL2424509,Homo sapiens,TP53-binding protein 1,9606,,,IC50,uM,UO_0000065,,10.0
,,13444886,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 mins by AlphaScreen assay,B,,,BAO_0000190,BAO_0000357,single protein format,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CCC(C5CCCN5)CC4)cc3Nc3ccccc3)cc2C1,,,CHEMBL2424619,J Med Chem,2013,"{'bei': '10.15', 'le': '0.19', 'lle': '-0.16', 'sei': '7.11'}",CHEMBL2426376,,CHEMBL2426376,5.46,0,http://www.openphacts.org/units/Nanomolar,1919665,=,1,1,=,,IC50,nM,,3500.0,CHEMBL2424509,Homo sapiens,TP53-binding protein 1,9606,,,IC50,uM,UO_0000065,,3.5
,,13444887,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 mins by AlphaScreen assay,B,,,BAO_0000190,BAO_0000357,single protein format,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CCC(C5CCCN5)CC4)cc3)cc2C1,,,CHEMBL2424619,J Med Chem,2013,,CHEMBL2426375,,CHEMBL2426375,,0,http://www.openphacts.org/units/Nanomolar,1919664,>,1,1,>,,IC50,nM,,10000.0,CHEMBL2424509,Homo sapiens,TP53-binding protein 1,9606,,,IC50,uM,UO_0000065,,10.0
,,13444888,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 mins by AlphaScreen assay,B,,,BAO_0000190,BAO_0000357,single protein format,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CC5CCC(C4)C5N4CCCC4)cc3)cc2C1,,,CHEMBL2424619,J Med Chem,2013,,CHEMBL2426374,,CHEMBL2426374,,0,http://www.openphacts.org/units/Nanomolar,1919663,>,1,1,>,,IC50,nM,,10000.0,CHEMBL2424509,Homo sapiens,TP53-binding protein 1,9606,,,IC50,uM,UO_0000065,,10.0
,,13444889,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 mins by AlphaScreen assay,B,,,BAO_0000190,BAO_0000357,single protein format,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CCC(N5CCCC5)CC4)cc3)cc2C1,,,CHEMBL2424619,J Med Chem,2013,,CHEMBL2426373,,CHEMBL2426373,,0,http://www.openphacts.org/units/Nanomolar,1919662,>,1,1,>,,IC50,nM,,10000.0,CHEMBL2424509,Homo sapiens,TP53-binding protein 1,9606,,,IC50,uM,UO_0000065,,10.0
,,13444890,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 mins by AlphaScreen assay,B,,,BAO_0000190,BAO_0000357,single protein format,O=C(c1ccc(C(=O)N2CCC(N3CCCC3)CC2)c(-c2ccccc2)c1)N1CCC(N2CCCC2)CC1,,,CHEMBL2424619,J Med Chem,2013,,CHEMBL2426368,,CHEMBL2426368,,0,http://www.openphacts.org/units/Nanomolar,1919657,>,1,1,>,,IC50,nM,,10000.0,CHEMBL2424509,Homo sapiens,TP53-binding protein 1,9606,,,IC50,uM,UO_0000065,,10.0
,,13444891,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 mins by AlphaScreen assay,B,,,BAO_0000190,BAO_0000357,single protein format,O=C(c1ccc(C(=O)N2CCC(N3CCCC3)CC2)c(Oc2ccccc2)c1)N1CCC(N2CCCC2)CC1,,,CHEMBL2424619,J Med Chem,2013,,CHEMBL2426367,,CHEMBL2426367,,0,http://www.openphacts.org/units/Nanomolar,1919656,>,1,1,>,,IC50,nM,,10000.0,CHEMBL2424509,Homo sapiens,TP53-binding protein 1,9606,,,IC50,uM,UO_0000065,,10.0
,,13444892,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 mins by AlphaScreen assay,B,,,BAO_0000190,BAO_0000357,single protein format,O=C(c1ccc(C(=O)N2CCC(N3CCCC3)CC2)c(Cc2ccccc2)c1)N1CCC(N2CCCC2)CC1,,,CHEMBL2424619,J Med Chem,2013,,CHEMBL2426366,,CHEMBL2426366,,0,http://www.openphacts.org/units/Nanomolar,1919655,>,1,1,>,,IC50,nM,,10000.0,CHEMBL2424509,Homo sapiens,TP53-binding protein 1,9606,,,IC50,uM,UO_0000065,,10.0
,,13444893,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 mins by AlphaScreen assay,B,,,BAO_0000190,BAO_0000357,single protein format,O=C(c1ccc(C(=O)N2CCC(N3CCCC3)CC2)c(NCc2ccccc2)c1)N1CCC(N2CCCC2)CC1,,,CHEMBL2424619,J Med Chem,2013,"{'bei': '9.31', 'le': '0.17', 'lle': '0.36', 'sei': '8.56'}",CHEMBL2426365,,CHEMBL2426365,5.06,0,http://www.openphacts.org/units/Nanomolar,1919654,=,1,1,=,,IC50,nM,,8700.0,CHEMBL2424509,Homo sapiens,TP53-binding protein 1,9606,,,IC50,uM,UO_0000065,,8.7

In [55]:
df1["standard_type"].isna().sum()

np.int64(0)

In [56]:
df2=df1[df1.standard_value.notna()]

In [57]:
df2.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,13444885,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 ...,B,None,None,BAO_0000190,...,Homo sapiens,TP53-binding protein 1,9606,None,None,IC50,uM,UO_0000065,None,10.0
1,None,None,13444886,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 ...,B,None,None,BAO_0000190,...,Homo sapiens,TP53-binding protein 1,9606,None,None,IC50,uM,UO_0000065,None,3.5
2,None,None,13444887,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 ...,B,None,None,BAO_0000190,...,Homo sapiens,TP53-binding protein 1,9606,None,None,IC50,uM,UO_0000065,None,10.0
3,None,None,13444888,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 ...,B,None,None,BAO_0000190,...,Homo sapiens,TP53-binding protein 1,9606,None,None,IC50,uM,UO_0000065,None,10.0
4,None,None,13444889,[],CHEMBL2429072,Inhibition of 53BP1 (unknown origin) after 30 ...,B,None,None,BAO_0000190,...,Homo sapiens,TP53-binding protein 1,9606,None,None,IC50,uM,UO_0000065,None,10.0

In [58]:
bioactivity_class=[]

In [64]:
for value in df2.standard_value:
  value=float(value)
  if value>=10000:
    bioactivity_class.append("inactive")
  elif value<=1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

In [65]:
molecule_ids=df2.molecule_chembl_id.tolist()
canonical_smiles=df2.canonical_smiles.tolist()
standard_value=df2.standard_value.tolist()

In [66]:
data=list(zip(molecule_ids,canonical_smiles,bioactivity_class,standard_value))

In [67]:
df3=pd.DataFrame(data,columns=["molecule_chembl_id","canonical_smiles","bioactivity_class","standard_value"])

In [68]:
df3.head()

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL2424677,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CCC(C5CCCN5)CC4)...,inactive,10000.0
1,CHEMBL2426376,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CCC(C5CCCN5)CC4)...,intermediate,3500.0
2,CHEMBL2426375,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CCC(C5CCCN5)CC4)...,inactive,10000.0
3,CHEMBL2426374,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CC5CCC(C4)C5N4CC...,inactive,10000.0
4,CHEMBL2426373,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CCC(N5CCCC5)CC4)...,inactive,10000.0

In [71]:
df3 = df3.dropna(subset=['canonical_smiles'])
df3 = df3[df3['canonical_smiles'].str.lower() != "none"]
df3 = df3[df3['canonical_smiles'].str.strip() != ""]
df3.head()

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL2424677,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CCC(C5CCCN5)CC4)...,inactive,10000.0
1,CHEMBL2426376,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CCC(C5CCCN5)CC4)...,intermediate,3500.0
2,CHEMBL2426375,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CCC(C5CCCN5)CC4)...,inactive,10000.0
3,CHEMBL2426374,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CC5CCC(C4)C5N4CC...,inactive,10000.0
4,CHEMBL2426373,CCN1Cc2ccc(NC(=O)c3ccc(C(=O)N4CCC(N5CCCC5)CC4)...,inactive,10000.0

In [87]:
df3.to_csv("bioactivity_preprocessed_data.csv", index=False)

In [88]:
!cp bioactivity_preprocessed_data.csv "/content/gdrive/MyDrive/Colab Notebooks/data"

In [89]:
!ls "/content/gdrive/MyDrive/Colab Notebooks/data"

'/content/gdrive/MyDrive/Colab Notebooks/data'